version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: httpd
    ports:
    - '8080:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
    networks:
    - apachehttp

networks:
  apachehttp: